import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import Providers from "@/context/Providers";
import SettingsNav from "@/components/settings/SettingsNav";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Settings",
    description: "Generated by create next app",
};


export default function SettingsLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    return (
        <html lang="en">
            <body className={`${inter.variable} relative flex flex-col min-h-screen antialiased`}>
                <Providers>
                    <div className='@container flex flex-col lg:flex-row items-start gap-4 md:gap-8'>
                        <SettingsNav />
                        <div className="flex-1 w-full h-full">
                            {children}
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}