import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import ReduxProviders from "@/redux/providers";
import GiverSettingsNav from "@/components/settings/settings-nav/GiverSettingsNav";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Giver Dashboard",
    description: "Generated by create next app",
};


export default function GiverDashboardLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    return (
        <html lang="en">
            <body className={`${inter.variable} relative flex flex-col min-h-screen antialiased`}>
                <ReduxProviders>
                    <div className='@container flex flex-col lg:flex-row items-start gap-4 md:gap-8'>
                        <GiverSettingsNav />
                        <div className="w-full h-full">
                            {children}
                        </div>
                    </div>
                </ReduxProviders>
            </body>
        </html>
    );
}