import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
// import Providers from "@/context/Providers";

import AuthScreenBanner from "@/components/auth/AuthScreenBanner";
import ReduxProviders from "@/redux/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "GTDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased`}
      >
        <ReduxProviders>
          <div className="min-h-screen lg:grid grid-cols-5 items-stretch">
            <AuthScreenBanner />
            <main className="grid col-span-3 bg-whiteP">
              {children}
            </main>
          </div>
        </ReduxProviders>
      </body>
    </html>
  );
}
