import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
// import Providers from "@/context/Providers";

import LoggedoutFixedHeader from "@/components/header/frontpage-headers/LoggedoutFixedHeader";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "GTDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <LoggedoutFixedHeader />
        {children}
      </body>
    </html>
  );
}
