import CreateAccountHeader from "@/components/header/CreateAccountHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "@/context/Providers";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Giver | Registration",
    description: "Generated by create next app",
};


export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    return (
        <html lang="en">
            <body className={`${inter.variable} flex flex-col  antialiased`}>
                <Providers>
                    <CreateAccountHeader />
                    {children}
                </Providers>
            </body>
        </html>
    );
}