import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "@/context/Providers";
import AuthScreenBanner from "@/components/auth/AuthScreenBanner";
import OnboardingHeader from "@/components/header/OnboardingHeader";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Giver | Registration",
    description: "Generated by create next app",
};


export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    return (
        <html lang="en">
            <body className={`${inter.variable} flex flex-col  antialiased`}>
                <Providers>
                    <div className="min-h-screen lg:grid grid-cols-5 items-stretch">
                        <AuthScreenBanner />
                        <main className="min-h-full grid col-span-3 bg-white overflow-y-auto">
                            <OnboardingHeader />
                            {children}
                        </main>
                    </div>
                </Providers>
            </body>
        </html>
    );
}