
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import ReduxProviders from "@/redux/providers";


import DashboardHeader from "@/components/header/DashboardHeader";
import SidebarSwitcher from "@/components/sidebar/SidebarSwitcher";
import SheetModal from "@/components/modal/Sheet";
import VerifyIdModal from "@/components/shared/VerifyId";
import AllBadges from "@/components/shared/AllBadges";
import UnmatchModalSequence from "@/components/shared/UnmatchModalSequence";
import Review from "@/components/shared/Review";
import AddItemModal from "@/components/multistep-form/AddItemModal";
import DisputeFlowModal from "@/components/shared/dispute";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function DashBoardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    
    return (
        <html lang="en">
            <body className={`${inter.variable} relative flex flex-col min-h-screen antialiased`}>
                <ReduxProviders>
                    <div className="relative flex h-full">
                        <SidebarSwitcher />
                        <div className="flex-1 flex flex-col min-h-dvh w-full">
                            <DashboardHeader />
                            <div className="w-full md:container flex-1 mx-auto px-4 py-6 md:px-6 lg:p-12">
                                {children}

                            </div>
                        </div>
                    </div>
                    <SheetModal />
                    <VerifyIdModal />
                    <AllBadges />
                    <UnmatchModalSequence />
                    <Review />
                    <AddItemModal />
                    <DisputeFlowModal />
                </ReduxProviders>
            </body>
        </html>
    );
}

