import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "@/context/Providers";
import DashboardHeader from "@/components/header/DashboardHeader";
import MenuSidebar from "@/components/sidebar/MenuSidebar";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};


export default function DashBoardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.ReactNode {
    return (
        <html lang="en">
            <body className={`${inter.variable} relative flex flex-col min-h-screen antialiased`}>
                <Providers>
                    <div className="relative flex h-full">
                        <MenuSidebar />
                        <div className="flex-1 h-full">
                            <DashboardHeader />
                            <div className="md:container mx-auto px-4 py-6 md:px-6 lg:p-12">
                                {children}
                            </div>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}